baseURL: "https://example.com"
languageCode: "en-us"
title: "HUSTMirrors"
pygmentsstyle: 'monokai'
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: hlug
theme: novela